<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HotelHup.CORE\HotelHup.CORE.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTO\room\" />
    <Folder Include="DTO\roomtype\" />
  </ItemGroup>

</Project>
